version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: blueprint
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/dhanush0x96c/blueprint/internal/version.Version={{.Version}}
      - -X github.com/dhanush0x96c/blueprint/internal/version.GitCommit={{.Commit}}
      - -X github.com/dhanush0x96c/blueprint/internal/version.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
